"""empty message

Revision ID: 98ff21592015
Revises: 5ace30e8e30c
Create Date: 2023-11-29 11:42:09.896676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ff21592015'
down_revision = '5ace30e8e30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'notes')
    # ### end Alembic commands ###
